			<div class="row-fluid sortable">
				<div class="box span12">
				  <div class="box-header" data-original-title>
					  <h2><i class="halflings-icon calendar"></i><span class="break"></span>Calendario Programación Torneo</h2>
				  </div>
				  <div class="box-content">
					<div id="external-events" class="span3 hidden-phone hidden-tablet">
						<h4>Rondas</h4>
						<div class="external-event badge">Primer Ronda</div>
						<div class="external-event badge badge-info">Segunda Ronda</div>
						<div class="external-event badge badge-success">Tercera Ronda</div>
						<div class="external-event badge badge-warning">Cuarta Ronda</div>
						<div class="external-event badge badge-important">Final</div>
						<p>
						<label for="drop-remove"><input type="checkbox" id="drop-remove" checked/> una sóla fecha</label>
						</p>
						</div>

						<div id="calendar" class="span9"></div>

						<div class="clearfix"></div>
					</div>
				</div>
			</div><!--/row-->